export type MerchantKnowledgeEntry = {
  canonicalName: string;
  aliases: string[];
  defaultCategory: string;
  defaultVatTreatment: "standard" | "zero_rated" | "exempt" | "out_of_scope" | "review";
  defaultReviewStatus?: "approved" | "needs_review";
  confidence?: number;
  reason?: string;
};

export const BASE_MERCHANT_KNOWLEDGE: MerchantKnowledgeEntry[] = [
  {
    canonicalName: "Uber Eats",
    aliases: ["uber eats", "pos purchase new uber eats", "uber eats 400568"],
    defaultCategory: "Staff Welfare / Meals / Entertainment",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 88,
    reason: "Known meal and entertainment merchant; VAT and invoice support require review.",
  },
  {
    canonicalName: "Mr D Food",
    aliases: ["mr d food", "mr d"],
    defaultCategory: "Staff Welfare / Meals / Entertainment",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 86,
    reason: "Food delivery merchant; keep VAT restricted/review until business purpose is confirmed.",
  },
  {
    canonicalName: "Google ChatGPT / OpenAI",
    aliases: ["google chatgpt", "chatgpt", "openai", "google openai"],
    defaultCategory: "Software Subscriptions",
    defaultVatTreatment: "standard",
    defaultReviewStatus: "needs_review",
    confidence: 90,
    reason: "Recurring software subscription merchant; invoice support still required for VAT.",
  },
  {
    canonicalName: "Google Xiaomi Home",
    aliases: ["google xiaomi home", "xiaomi home"],
    defaultCategory: "Software / IT",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 84,
    reason: "Google/Xiaomi app-service merchant; account is IT/software but VAT remains review.",
  },
  {
    canonicalName: "Google",
    aliases: ["google", "google cloud", "google workspace", "google play", "google storage"],
    defaultCategory: "Software / IT",
    defaultVatTreatment: "standard",
    defaultReviewStatus: "needs_review",
    confidence: 84,
    reason: "Google merchant pattern; require invoice support before final VAT claim.",
  },
  {
    canonicalName: "Microsoft",
    aliases: ["microsoft", "office365", "microsoft 365", "msft"],
    defaultCategory: "Software / IT",
    defaultVatTreatment: "standard",
    defaultReviewStatus: "needs_review",
    confidence: 86,
    reason: "Software subscription merchant; invoice support required for VAT.",
  },
  {
    canonicalName: "Adobe",
    aliases: ["adobe"],
    defaultCategory: "Software / IT",
    defaultVatTreatment: "standard",
    defaultReviewStatus: "needs_review",
    confidence: 86,
    reason: "Software subscription merchant; invoice support required for VAT.",
  },
  {
    canonicalName: "Amazon Web Services",
    aliases: ["amazon web services", "aws", "amazon aws"],
    defaultCategory: "Software / IT",
    defaultVatTreatment: "standard",
    defaultReviewStatus: "needs_review",
    confidence: 86,
    reason: "Cloud software merchant; invoice support required for VAT.",
  },
  {
    canonicalName: "FNB Bank Charges",
    aliases: ["byc debit", "monthly account fee", "service fees", "#service fees", "cash deposit fee", "excess item fee", "accrued bank charge"],
    defaultCategory: "Bank Charges",
    defaultVatTreatment: "standard",
    defaultReviewStatus: "approved",
    confidence: 98,
    reason: "FNB fee pattern; bank-charge VAT treatment can be taken from the bank tax invoice.",
  },
  {
    canonicalName: "DHL",
    aliases: ["dhl", "paygate dhl", "paygate*dhl", "courier guy", "the courier guy", "aramex", "postnet"],
    defaultCategory: "Courier / Delivery",
    defaultVatTreatment: "standard",
    defaultReviewStatus: "needs_review",
    confidence: 88,
    reason: "Courier and delivery supplier; invoice support required for VAT.",
  },
  {
    canonicalName: "Discovery",
    aliases: ["discovery account", "discovery insure", "discovery insurance", "discovery health"],
    defaultCategory: "Insurance",
    defaultVatTreatment: "exempt",
    defaultReviewStatus: "approved",
    confidence: 94,
    reason: "Known insurance/medical supplier pattern.",
  },
  {
    canonicalName: "Salaries and Caregivers",
    aliases: ["salary", "payroll", "wages", "nanny", "care giver", "caregiver", "sunfield sureka reddy", "brilliant care giver", "ana care giver", "waterfall salary"],
    defaultCategory: "Salaries & Wages",
    defaultVatTreatment: "out_of_scope",
    defaultReviewStatus: "approved",
    confidence: 94,
    reason: "Payroll or caregiver payment pattern; no VAT claim.",
  },
  {
    canonicalName: "Inter-account Transfers",
    aliases: ["fnb app transfer to savings", "fnb app transfer from credit", "transfer to savings", "transfer from credit", "own account", "inter-account"],
    defaultCategory: "Inter-account Transfer",
    defaultVatTreatment: "out_of_scope",
    defaultReviewStatus: "approved",
    confidence: 95,
    reason: "Own-account transfer pattern; excluded from VAT and profit/loss.",
  },
  {
    canonicalName: "SARS",
    aliases: ["sars", "efiling", "paye", "vat201", "provisional tax", "tax deposit"],
    defaultCategory: "SARS / Tax Suspense",
    defaultVatTreatment: "out_of_scope",
    defaultReviewStatus: "approved",
    confidence: 92,
    reason: "Tax authority payment/receipt; classify to tax suspense, not revenue.",
  },
  {
    canonicalName: "Government Health / Tender Receipts",
    aliases: [
      "magtape credit 047-gp hea",
      "gp hea",
      "gauteng health",
      "department of health",
      "dept of health",
      "health department",
    ],
    defaultCategory: "Sales / Revenue",
    defaultVatTreatment: "standard",
    defaultReviewStatus: "needs_review",
    confidence: 94,
    reason: "Inbound government or tender/service receipt; review output VAT and supporting invoice before final filing.",
  },
  {
    canonicalName: "Savings and Home Loan Transfers",
    aliases: ["scheduled payment to savings", "money maximizer savings", "transfer to credit card", "fnb app transfer to credit card", "scheduled payment to home loan", "transfer to home loan", "home loan payment"],
    defaultCategory: "Loan / Liability",
    defaultVatTreatment: "out_of_scope",
    defaultReviewStatus: "approved",
    confidence: 92,
    reason: "Balance-sheet transfer or loan repayment pattern; excluded from VAT and profit/loss.",
  },
  {
    canonicalName: "Sage Accounting",
    aliases: ["sage sa", "sage acc", "sage accounting", "pos purchase sage"],
    defaultCategory: "Software Subscriptions",
    defaultVatTreatment: "standard",
    defaultReviewStatus: "needs_review",
    confidence: 90,
    reason: "Known accounting software subscription; invoice support required for VAT.",
  },
  {
    canonicalName: "Accounting and Professional Fees",
    aliases: ["acapolite accounting", "accounting", "bookkeeping", "audit fee", "tax practitioner"],
    defaultCategory: "Accounting / Professional Fees",
    defaultVatTreatment: "standard",
    defaultReviewStatus: "needs_review",
    confidence: 88,
    reason: "Professional accounting service supplier; invoice support required for VAT.",
  },
  {
    canonicalName: "Netcash Debit Orders",
    aliases: ["netcash", "stratum netcash", "magtape debit stratum", "disc prem", "magtape debit disc prem"],
    defaultCategory: "Operating Expenses",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 76,
    reason: "Recurring debit-order supplier pattern; category is operational but supporting detail is needed.",
  },
  {
    canonicalName: "Supplier Payments",
    aliases: [
      "jc industries",
      "bambhanani enterpris",
      "first works",
      "industries allianz holdings",
      "fabric and leather",
      "world focus",
      "kenny s intermedia",
      "rmsp trading",
      "rmsp trading allianz holdings",
      "stalitrex",
      "stalitrex allianz holdings",
      "nms enterprises",
      "nms enterprises 5290b",
    ],
    defaultCategory: "Supplier Payments",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 86,
    reason: "Named supplier/company payment pattern; invoice support required before final VAT treatment.",
  },
  {
    canonicalName: "IT and Electronics Suppliers",
    aliases: ["samsung electronics", "global-e", "google xiaomi home", "xiaomi home"],
    defaultCategory: "Software / IT",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 82,
    reason: "Technology or electronics merchant; classify to IT with VAT review.",
  },
  {
    canonicalName: "Medical Pharmacy and Hair Suppliers",
    aliases: ["sunnydale pharm", "pharmacy", "khumbu hair", "raquel hair", "hair stuff", "hair health"],
    defaultCategory: "Staff Welfare / Meals / Entertainment",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 72,
    reason: "Personal-care or pharmacy supplier; keep in review until business purpose is confirmed.",
  },
  {
    canonicalName: "Emporers Ridge Levy",
    aliases: ["emporers ridge levy", "emporers ridge h oa", "body corporate", "hoa levy", "levy"],
    defaultCategory: "Levies",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 86,
    reason: "Property/body-corporate levy pattern; VAT depends on supporting document.",
  },
  {
    canonicalName: "Takealot",
    aliases: ["takealot"],
    defaultCategory: "Uncategorised Expense",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 70,
    reason: "Retail merchant; needs review because goods may be personal, inventory, office, or capital.",
  },
  {
    canonicalName: "Eskom",
    aliases: ["eskom"],
    defaultCategory: "Utilities",
    defaultVatTreatment: "standard",
    defaultReviewStatus: "needs_review",
    confidence: 88,
    reason: "Utility supplier; invoice support required for VAT.",
  },
  {
    canonicalName: "Checkers",
    aliases: ["checkers", "checkers sixty60"],
    defaultCategory: "Staff Welfare / Meals / Entertainment",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 76,
    reason: "Grocery/retail merchant; possible personal or entertainment spend.",
  },
  {
    canonicalName: "Woolworths",
    aliases: ["woolworths"],
    defaultCategory: "Staff Welfare / Meals / Entertainment",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 76,
    reason: "Grocery/retail merchant; possible personal or entertainment spend.",
  },
  {
    canonicalName: "Clicks",
    aliases: ["clicks"],
    defaultCategory: "Staff Welfare / Meals / Entertainment",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 74,
    reason: "Pharmacy/retail merchant; expense purpose needs review.",
  },
  {
    canonicalName: "Dis-Chem",
    aliases: ["dis chem", "dis-chem"],
    defaultCategory: "Staff Welfare / Meals / Entertainment",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 74,
    reason: "Pharmacy/retail merchant; expense purpose needs review.",
  },
  {
    canonicalName: "Personal / Lifestyle Review Suppliers",
    aliases: ["senses spa", "adore photography", "sloppy kisses", "puppy classes", "prayer shop"],
    defaultCategory: "Review Required",
    defaultVatTreatment: "review",
    defaultReviewStatus: "needs_review",
    confidence: 62,
    reason: "Personal-looking or ambiguous supplier; accountant review required.",
  },
];
